---
conda:
  path: /mnt/gvl/apps/anaconda_ete/bin
  environments:
  - 
    name: beatson_py2_ver
    state: present
    channels: 
      - bioconda
      - conda-forge
      - r
    dependencies:
      - python=2
      - abricate=0.3
      - aragorn=1.2.36
      - barrnap=0.7
      - bedtools=2.26.0
      - bwa=0.7.15
      - cd-hit=4.6.6
      - eigensoft=6.0.1
      - exonerate=2.2.0
      - fasttree=2.1.8
      - flex=2.6.0
      - freebayes=1.0.2
      - hmmer=3.1b2
      - infernal=1.1.1
      - isl=0.15
      - mafft=7.221
      - mash=1.1
      - megahit=1.0.3
      - minced=0.2.0
      - mlst=2.6
      - numpy=1.11.2
      - poretools=0.6.0
      - prodigal=2.6.2
      - prokka=1.11
      - raxml=8.2.9
      - samtools=0.1.18
      - skewer=0.2.2
      - snippy=3
      - snpeff=4.2
      - spades=3.9.0
      - srst2=0.2.0
      - trimmomatic=0.36
      - vcflib=1.0.0_rc0
      - velvet=1.2.10
      - cmake=3.6.1
      - libpng=1.6.26
      - libtool=2.4.6
      - libxml2=2.9.4
      - pcre=8.38
      - vcftools=0.1.14
  -
    name: beatson_py3_ver
    state: present
    channels:
      - bioconda
      - conda-forge
      - r
    dependencies:
      - python=3
      - samtools=1.3.1
      - unicycler=0.2.0
  -
    name: beatson_py2_test
    state: present
    channels:
      - bioconda
      - conda-forge
      - r
    dependencies:
      - python=2
      - abricate=0.3
      - aragorn=1.2.36
      - barrnap=0.7
      - bedtools=2.26.0
      - bwa=0.7.15
      - cd-hit=4.6.6
      - eigensoft=6.0.1
      - exonerate=2.2.0
      - fasttree=2.1.8
      - flex=2.6.0
      - freebayes=1.0.2
      - hmmer=3.1b2
      - infernal=1.1.1
      - isl=0.15
      - mafft=7.221
      - mash=1.1
      - megahit=1.0.3
      - minced=0.2.0
      - mlst=2.6
      - numpy=1.11.2
      - poretools=0.6.0
      - prodigal=2.6.2
      - prokka=1.11
      - raxml=8.2.9
      - samtools=0.1.18
      - skewer=0.2.2
      - snippy=3
      - snpeff=4.2
      - spades=3.9.0
      - srst2=0.2.0
      - trimmomatic=0.36
      - vcflib=1.0.0
      - velvet=1.2.10
      - cmake=3.6.1
      - libpng=1.6.26
      - libtool=2.4.6
      - libxml2=2.9.4
      - pcre=8.38
      - bcftools=1.2
      - blast=2.5.0
      - blat=35
      - bowtie2=2.3.0
      - cmake=3.6.1
      - expat=2.1.0
      - libpng=1.6.26
      - libtiff=4.0.6
      - libtool=2.4.6
      - libxcb=1.12
      - libxml2=2.9.4
      - pcre=8.38
      - prank=v.150803
      - roary=3.7.0
      - tbl2asn=25.0
      - vcftools=0.1.14
  environments.test:
  - 
    name: stats1
    state: absent
    dependencies:
      - bokeh
  remove:
  -
    name: test
    state: remove_env