---
conda:
  path: /mnt/gvl/apps/anaconda_ete/bin
  environments:
  - 
    name: beatson_py2_ver
    state: present
    channels: 
      - qfab
      - bioconda
      - conda-forge
      - r
    dependencies:
      - python=2
      - abricate=0.3
      - aragorn=1.2.36
      - barrnap=0.7
      - bedtools=2.26.0
      - bison=3.0.4
      - bwa=0.7.15
      - cairo=1.14.6
      - cd-hit=4.6.6
      #- eigensoft=6.0.1 #not available on OS X
      #- exonerate=2.2.0 #not available on OS X
      #- fasttree=2.1.8 #alt version for OS X
      - fasttree=2.1.9
      - fastx_toolkit=0.0.14
      - flex=2.6.0
      - freebayes=1.0.2
      - hmmer=3.1b2
      - infernal=1.1.1
      - isl=0.15
      #- kraken=0.10.5beta #alt version for OS X
      - kraken-biom=1.0.1
      - mafft=7.221
      - mash=1.1
      #- megahit=1.0.3 #not available on OS X
      - minced=0.2.0
      - mlst=2.6
      - numpy=1.11.2
      - picard=2.5.0
      - poretools=0.6.0
      - prodigal=2.6.2
      - prokka=1.11
      - raxml=8.2.9
      - samtools=0.1.18
      - skewer=0.2.2
      - snippy=3
      - snpeff=4.2
      - spades=3.9.0
      - srst2=0.2.0
      - trimmomatic=0.36
      - vcflib=1.0.0_rc0
      - velvet=1.2.10
      - cmake=3.6.1
      - libpng=1.6.26
      - libtool=2.4.6
      - libxml2=2.9.4
      - pixman=0.34.0
      - pcre=8.38
      - unzip=6.0
      - vcftools=0.1.14
      - xorg-kbproto=1.0.7
      - xorg-libx11=1.6.4
      - xorg-libxau=1.0.8
      - xorg-xextproto=7.3.0
      - xorg-xproto=7.0.31
      - xorg-xtrans=1.3.5
      - blat=36
      #- dsk=2.1.0 #alt version for OS X
      - dsk=2.2.0
      - imagemagick=7.0.5
      #- newick-utils=1.6 #alt channel for OS X
      - newick_utils=1.6
      #- phyml=3.2.0 #alt channel for OS X
      - phyml=3.2.20160530
  -
    name: beatson_py3_ver
    state: present
    channels:
      - bioconda
      - conda-forge
      - r
    dependencies:
      - python=3
      - samtools=1.3.1
      - unicycler=0.2.0
  -
    name: beatson_py2_test
    state: present
    channels:
      - bioconda
      - conda-forge
      - r
    dependencies:
      - python=2
      - abricate=0.3
      - aragorn=1.2.36
      - barrnap=0.7
  -
    name: beatson_banzai_dev
    state: present
    channels:
      - bioconda
      - conda-forge
      - r
    dependencies:
      - python=2.7
      - fabric=1.10.0
      - matplotlib=2.0.0
      - biopython=1.68
      - git=2.8.2
      - sphinx=1.5.3
      - screed=0.9
      - ete2=2.3.10
      #### needs 'finder' too from apt-get

  environments.test:
  - 
    name: stats1
    state: absent
    dependencies:
      - bokeh
  remove:
  -
    name: test
    state: remove_env