---

# update conda
- name: Update Conda package manager
  become: true
  become_user: root
  conda:
    update_conda: true
  tags: conda
  
# For states "present" and "absent"
# Requires name, state and dependencies
- name: Process Conda environments
  become: true
  become_user: root
  conda:
    name: "{{ item.name }}"
    path: "{{ conda.path }}"
    state: "{{ item.state }}"
    channels: "{{ item.channels | default('') }}"
    dependencies: "{{ item.dependencies }}"
  with_items: "{{ conda.environments }}"
  tags: conda

# separated, due to seriousness of removal
- name: Remove Conda environments
  become: true
  become_user: root
  conda:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ conda.remove }}"
  tags: conda

