---
#- name: Unlink brew packages
#  homebrew: name={{ item.name }}
#            state=unlinked
#            path={{ linuxbrew_path }}
#  with_items: "{{ linuxbrew_packages }}"
#  environment:
#    PATH: "{{ linuxbrew_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
#  sudo: no

- name: Install brew packages (CLI)
  shell: (brew unlink {{ item.name }} || true) && brew install {{ item.path }}
  args:
    creates: "{{ linuxbrew_home }}/.linuxbrew/Cellar/{{ item.name }}/{{ item.version }}"
  with_items: "{{ linuxbrew_packages }}"
  environment:
    PATH: "{{ linuxbrew_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"

#- name: Re-link brew packages
#  homebrew: name={{ item.name }}
#            state=linked
#            path={{ linuxbrew_path }}
#  with_items: "{{ linuxbrew_packages }}"
#  environment:
#    PATH: "{{ linuxbrew_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
#  sudo: no