---
- name: Install brew packages (CLI)
  shell: (brew unlink {{ item.name }} || true) && brew install {{ item.path }}
  args:
    creates: "{{ linuxbrew_home }}/.linuxbrew/Cellar/{{ item.name }}/{{ item.version }}"
  with_items: "{{ linuxbrew_packages }}"
  environment:
    PATH: "{{ linuxbrew_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
  register: brew

  - name: Relink any failed brew installs (CLI)
    shell: (brew link {{ item.item.name }} || true)
    when: item.rc != 0
    with_items: "{{ brew.results }}"
