---
- name: Install brew packages (CLI)
  linuxbrew:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    latest: false
    recipe: "{{ item.path }}"
    state: present
  with_items: "{{ linuxbrew_packages }}"
#  ignore_errors: yes
  environment:
    PATH: "{{ linuxbrew_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"

# Probably won't need this
# Work detection into linuxbrew module
#- name: Verify brew versions installed
#  linuxbrew: echo "{{ item.name }} {{ item.version }} not installed" && false
#    name: "{{ item.name }}"
#    version: "{{ item.version }}"
#    state: present
#  with_items: "{{ linuxbrew_packages }}"
