---
- name: Set the server's hostname
  become: true
  hostname: name="{{ inventory_hostname }}"
  when: ansible_distribution == "Ubuntu"

- name: Update hosts file
  become: true
  lineinfile: 
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
  
- name: Add user ssh keys
  authorized_key: user="{{ item.name }}" key="{{ lookup('file', '../' + item.key) }}"
  with_items: "{{ users }}"
  when: item.key is defined
  tags:
    - users
    - keys

- name: Remove revoked user ssh keys
  authorized_key: user="{{ item.name }}" key="{{ lookup('file', '../' + item.delete_key) }}" state=absent
  with_items: "{{ users }}"
  when: item.delete_key is defined
  tags:
    - users
    - keys

- name: Disable SSH password logins
  become: true
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  notify: Restart sshd
  tags: ssh

- name: Upload the SSH banner
  become: true
  copy: dest=/etc/ssh/ssh_banner src=../files/ssh_banner
  tags: ssh

- name: Set the SSH banner
  become: true
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?Banner" line="Banner /etc/ssh/ssh_banner"
  notify: Restart sshd
  tags: ssh

- name: Update apt cache
  become: true
  apt: update_cache=yes cache_valid_time=900
  tags: apt

- name: Install common packages
  become: true
  apt: name="{{ item }}" state=present
  with_items:
    - tmux
    - vim
    - zsh
    - logrotate
    - build-essential
    - curl
    - git
    - python-setuptools
    - ruby
  tags:
    - apt

- include: vim.yml

# Don't have a GVL Ubuntu 16.04 to test this on; limit to 14.04 ~tc
- name: Add Logrotate to cron table
  become: true
  cron: name="run logrotate" minute="0" hour="1" job="/usr/sbin/logrotate /etc/logrotate.conf > /dev/null 2>&1"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

#- include: linuxbrew.yml
- include: conda.yml
