- hosts: all
  remote_user: ubuntu
  vars:
    galaxy_tools_tool_list_files:
    - "../files/tool_list_all.yaml"
    galaxy_tools_galaxy_instance_url: http://127.0.0.1:8080/
  roles:
    - ../roles/common
    #- galaxyprojectdotorg.galaxy-tools
