- hosts: all
  remote_user: ubuntu
  become_user: root
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  roles:
    - role: debops.users
      become: True
      tags: [ 'role::users' ]
    - ../roles/common
